# Generated by Django 3.1 on 2020-10-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_mascota', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_mascota',
            },
        ),
    ]
