# Generated by Django 3.1 on 2020-10-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
        ('raza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='razas', to='tipo.tipomascota'),
        ),
    ]
