# Generated by Django 3.1 on 2020-10-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raza', '0002_auto_20201009_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
